# Cauldron Rework Configuration
# ----------------------------

# General cauldron mechanics
enable-ice: true
enable-honey: true
enable-remove-dye: true

# Copper Hopper
copper-hopper: true
# Items ejected before the hopper losses its wax layer (0 = never, 1000 = Default)
copper-hopper-item-count: 1000

# Settings for dispenser-to-cauldron interactions
allow-from-below: true
enable-water: true
enable-lava: true
enable-powder-snow: true

# Miscellaneous gameplay tweaks

# Glistering Melons become edible and give a short regeneration effect
enable-edible-glistering-melon: true

banner-on-boats: true
banner-on-beds: true
husks-drop-sand: true
goat-drop-mutton: true
