# Cauldron Rework Configuration
# ----------------------------

# General cauldron mechanics
cauldrons:
  enable-ice: true
  enable-honey: true
  enable-remove-dye: true

# Settings for dispenser-to-cauldron interactions
dispenser-interaction:
  allow-from-below: true
  enable-water: true
  enable-lava: true
  enable-powder-snow: true

# Miscellaneous gameplay tweaks
mechanics:
  # Glistering Melons become edible and give a short regeneration effect
  edible-glistering-melon: true
